const clothes = [
  {
    id: 0,
    type: 'clothes',
    img: 'assets/image04.jpg',
    alt: 'Футболка "Эволюционируй или сдохни"',
    title: 'Футболка "Эволюционируй или сдохни"',
    price: 220,
    badge: true,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 1,
    type: 'clothes',
    img: 'assets/image11.jpg',
    alt: 'Футболка "Все очень круто, но надо переделать"',
    title: 'Футболка "Все очень круто, но надо переделать"',
    price: 200,
    badge: true,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 5,
    type: 'clothes',
    img: 'assets/image12.jpg',
    alt: 'Толстовка "Kolesa Team"',
    title: 'Толстовка "Kolesa Team"',
    price: 500,
    badge: false,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 6,
    type: 'clothes',
    img: 'assets/image13.jpg',
    alt: 'Толстовка "Kolesa Team"',
    title: 'Толстовка "Kolesa Team"',
    price: 510,
    badge: false,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 7,
    type: 'clothes',
    img: 'assets/image14.jpg',
    alt: 'Толстовка "Kolesa Team"',
    title: 'Толстовка "Kolesa Team"',
    price: 520,
    badge: false,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 8,
    type: 'clothes',
    img: 'assets/image17.png',
    alt: 'Толстовка "Kolesa Team"',
    title: 'Толстовка "Kolesa Team"',
    price: 525,
    badge: false,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
];

const accessories = [
  {
    id: 11,
    type: 'accessories',
    img: 'assets/image07.jpg',
    alt: 'Бутылка для воды',
    title: 'Бутылка для воды',
    price: 150,
    badge: false,
    size: 'M',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 13,
    type: 'accessories',
    img: 'assets/image15.jpg',
    alt: 'Рюкзак "Kolesa Team"',
    title: 'Рюкзак "Kolesa Team"',
    price: 400,
    badge: true,
    size: 'M',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 14,
    type: 'accessories',
    img: 'assets/image16.jpg',
    alt: 'Рюкзак "Kolesa Team"',
    title: 'Рюкзак "Kolesa Team"',
    price: 390,
    badge: true,
    size: 'M',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 15,
    type: 'accessories',
    img: 'assets/image08.jpg',
    alt: 'Термо-кружка "Kolesa Team"',
    title: 'Термо-кружка "Kolesa Team"',
    price: 380,
    badge: false,
    size: 'M',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 16,
    type: 'accessories',
    img: 'assets/image09.jpg',
    alt: 'Вязанная шапка "Kolesa Team"',
    title: 'Вязанная шапка "Kolesa Team"',
    price: 230,
    badge: false,
    size: 'S/M/L',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
  {
    id: 17,
    type: 'accessories',
    img: 'assets/image20.jpg',
    alt: 'Солнцезащитные очки',
    title: 'Солнцезащитные очки',
    price: 100,
    badge: false,
    size: 'M',
    desc: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
  },
];

export { clothes, accessories };
